categories:
  LDO:
    rank: 1
  LED:
    rank: 1
  MOSFET:
    rank: 0
  MSP430:
    rank: 1
  RF:
    rank: 0
  Schottky:
    rank: 1
  USB:
    rank: 1
  Zener:
    rank: 1
  antenna:
    rank: 1
  capacitor:
    rank: 1
  connector:
    rank: 0
  crystal:
    rank: 1
  digital:
    rank: 0
  diode:
    rank: 0
  gate:
    rank: 1
  inductor:
    rank: 1
  microcontroller:
    rank: 0
  nmos:
    rank: 1
  passive:
    rank: 0
  pmos:
    rank: 1
  power:
    rank: 0
  resistor:
    rank: 1
  sensor:
    rank: 0
  slide:
    rank: 1
  switch:
    rank: 0
  temperature:
    rank: 1
  transceiver:
    rank: 1
  instrument:
    rank: 0
    hide: true

footer: "Your Name, [GitHub](https://github.com/yourname), version: #TODAY"
footer_timestamp: "%d.%m.%Y"
md_extensions:
  - extra
  - codehilite
  - toc
  - tables
  - fenced_code
sftp_hostname: test.com
sftp_port: 22
sftp_user: user
sftp_password: 1234
sftp_path: "/var/www/"
